// AUTH 

export const AUTH_USER = "AUTH/AUTH_USER"
export const LOG_OUT = "AUTH/LOG_OUT"
export const TOGGLE_AUTH = "AUTH/TOGGLE_AUTH"
export const SIGN_IN_ERR = "AUTH/SIGN_IN_ERR"
export const SIGN_UP_ERR = "AUTH/SIGN_UP_ERR"

// LOADING

export const TOGGLE_LOADING = "LOADING/TOGGLE_LOADING"

// SEARCH

export const SEARCHED_DATA = "SEARCH/SEARCHED_DATA"

// PRODUCTS

export const SET_PRODUCT = "PRODUCTS/SET_PRODUCT"
export const SET_PRODUCT_ERROR = "PRODUCTS/SET_PRODUCT_ERROR"
export const SET_PRODUCT_LOADING_TRUE = "PRODUCTS/SET_PRODUCT_LOADING_TRUE"
export const SET_PRODUCT_LOADING_FALSE = "PRODUCTS/SET_PRODUCT_LOADING_FALSE"
export const SET_FEATURED_PRODUCT = "PRODUCTS/SET_FEATURED_PRODUCT"
export const RESET_ACTIVE_PRODUCT = "PRODUCTS/RESET_ACTIVE_PRODUCT"
export const SET_LOADED_PRODUCT = "PRODUCTS/SET_LOADED_PRODUCT"
export const SET_SEARCHED_PRODUCT = "PRODUCTS/SET_SEARCHED_PRODUCT"
export const UPDATE_PARAMS = "PRODUCTS/UPDATE_PARAMS"

// PARTNERS


export const SET_PARTNERS = "PARTNERS/SET_PARTNERS"
export const RESET_PARTNERS = "PARTNERS/RESET_PARTNERS"
export const SET_PARTNERS_ERROR = "PARTNERS/SET_PARTNERS_ERROR"
export const SET_PARTNERS_LOADING_TRUE = "PARTNERS/SET_PARTNERS_LOADING_TRUE"
export const SET_PARTNERS_LOADING_FALSE = "PARTNERS/SET_PARTNERS_LOADING_FALSE"

// CAROUSEL

export const SET_BANNERS = "CAROUSEL/SET_BANNERS"
export const RESET_BANNERS = "CAROUSEL/RESET_BANNERS"
export const SET_BANNERS_ERROR = "CAROUSEL/SET_BANNERS_ERROR"
export const SET_BANNERS_LOADING_TRUE = "CAROUSEL/SET_BANNERS_LOADING_TRUE"
export const SET_BANNERS_LOADING_FALSE = "CAROUSEL/SET_BANNERS_LOADING_FALSE"
